import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Navigation } from "@/src/components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({ 
  children, 
}: {
    children: React.ReactNode
  }) {
  return (
      <html lang="en">
        <body className="grid min-h-screen flex flex-col">
          <div className="grid min-h-full">
            {children}
          </div>
          <footer className="bg-black text-white w-full text-2xl my-2 font-bold grid">
            <p className="justify-self-center self-center">Footer</p>
          </footer>
        </body>
      </html>
  )
}